name: Pull request to main

on:
  pull_request:
    branches:
    - main

jobs:
  enforce_git_lfs:
    runs-on: ubuntu-latest
    steps:
    - name: LFS Check
      uses: MPLew-is/lfs-check-action@1.0.0
